<a href="https://colab.research.google.com/github/AbhishekKurra/Hands-On15/blob/main/Floyd-Warshall%20algorithm%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

def floyd_warshall(graph):

    num_vertices = len(graph)
    distance = np.array(graph, copy=True)
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i, k] + distance[k, j] < distance[i, j]:
                    distance[i, j] = distance[i, k] + distance[k, j]

    return distance

if __name__ == '__main__':
    graph = [
        [0, 2, np.inf, 6],
        [7, 0, 2, np.inf],
        [4, np.inf, 0, 3],
        [1, np.inf, np.inf, 0]
    ]

    shortest_paths = floyd_warshall(graph)
    print("Shortest paths between all pairs of vertices:")
    print(shortest_paths)
    graph_negative = [
        [0, 1, np.inf],
        [np.inf, 0, -3],
        [1, np.inf, 0]
    ]

    shortest_paths_negative = floyd_warshall(graph_negative)
    print("\nShortest paths with negative edge weights:")
    print(shortest_paths_negative)



Shortest paths between all pairs of vertices:
[[0. 2. 4. 6.]
 [6. 0. 2. 5.]
 [4. 6. 0. 3.]
 [1. 3. 5. 0.]]

Shortest paths with negative edge weights:
[[-1.  0. -3.]
 [-2. -1. -4.]
 [ 0.  1. -2.]]
